# Snakefile

# the configuration file, stores the seq ID
configfile: "config/config.yaml"

# extract the SRA id
Read_id = config["ID"]
# extract the lineage dataset for BUSCO analysis
Dataset = config["Dataset"]

rule all:
    input:
        f"results/01_fastqc/{Read_id}_fastqc.html",
        f"results/03_quast/{Read_id}/report.html",
        directory(f"results/04_busco")

# Download the fastq read data using SRA-tool
rule generate_fastq:
    output:
        fastq=f"resources/{Read_id}/{Read_id}.fastq"
    conda:
        "envs/sratools.yaml"
    threads: 10
    shell:
        """
        mkdir -p resources/{Read_id}
        fasterq-dump {Read_id} -O resources/{Read_id} -e {threads}   # the fasterq-dump is used to extract the sequence from the NCBI
        """

# Perform the quality assessment using fastqc
rule fastqc:
    input:
        fastq=rules.generate_fastq.output.fastq
    output:
       html=f"results/01_fastqc/{Read_id}_fastqc.html",
       zip=f"results/01_fastqc/{Read_id}_fastqc.zip"
    threads: 8
    wrapper:
        "0.85.0/bio/fastqc"         # snakemake wrapper is used to generate fastqc

# Perform the denovo assembly
rule de_novo:
    input:
        fastq=rules.generate_fastq.output.fastq
    output:
        gfa=f"results/02_assembly/{Read_id}.bp.p_ctg.gfa"
    conda:
        "envs/assembly.yaml"
    params:
        prefix=f"results/02_assembly/{Read_id}"
    threads: 30
    shell:
        """
        mkdir -p results/02_assembly
        hifiasm -o {params.prefix} -t {threads} {input.fastq} 
        """

# convert .gfa to .fa
rule convert_gfa:
    input:
        gfa=rules.de_novo.output.gfa
    output:
        fa=f"results/02_assembly/{Read_id}.bp.p_ctg.fa"
    shell:
        """
        awk '/^S/{{print ">"$2"\\n"$3}}' {input.gfa} > {output.fa}          # converting the gfa to fa (fasta format)
        """

# genome assembly quality check by quast
rule assembly_check1:
    input:
        fasta=rules.convert_gfa.output.fa
    output:
        report=f"results/03_quast/{Read_id}/report.html"
    threads: 15
    params:
        prefix=f"results/03_quast/{Read_id}"
    conda:
        "envs/quast.yaml"
    shell:
        """
        mkdir -p results/03_quast/{Read_id}
        quast {input.fasta} -o {params.prefix}
        """

# download the reference genome
rule download_reference:
    output:
         out_dir=directory(f"resources/busco_downloads")
    params:
        lineage=Dataset,
        prefix=f"resources/busco_downloads"
    conda:
        "envs/busco.yaml"
    shell:         
         """
         busco --download {params.lineage} 
        """
# genome assembly check by BUSCO
rule assembly_check2:
    input:
        fasta=rules.convert_gfa.output.fa,
        data=rules.download_reference.output.out_dir
    output:
        out_dir=directory(f"results/04_busco")
    threads: 15
    params:
        mode="genome",
        lineage=Dataset
    conda:
        "envs/busco.yaml"
    shell:
        """
        mkdir -p results/04_busco
        mkdir -p {params.download_path}

        # Run BUSCO
        busco \
            -i {input.fasta} \
            -o {Read_id} \
            --out_path {output.out_dir} \
            -l {params.lineage} \
            -m {params.mode} \
            --cpu {threads} \
            --download_path {params.download_path} \
            --force
        """
    
        


