
# the configuration file, stores the seq ID
configfile: "config/config.yaml"

# extract the SRA id
Read_id = config["ID"]

rule all:
    input:
        f"results/01_fastqc/{Read_id}_fastqc.html",
        f"results/03_quast/{Read_id}/report.html"

# Download the fastq read data using SRA-tool
rule generate_fastq:
    output:
        fastq=f"resources/{Read_id}/{Read_id}.fastq"
    conda:
        "envs/sratools.yaml"
    threads: 10
    shell:
        """
        mkdir -p resources/{Read_id}
        fasterq-dump {Read_id} -O resources/{Read_id} -e {threads}
        """

# Perform the quality assessment using fastqc
rule fastqc:
    input:
        fastq=rules.generate_fastq.output.fastq
    output:
       html=f"results/01_fastqc/{Read_id}_fastqc.html",
       zip=f"results/01_fastqc/{Read_id}_fastqc.zip"
    threads: 8
    wrapper:
        "0.85.0/bio/fastqc"

# Perform the denovo assembly
rule de_novo:
    input:
        fastq=rules.generate_fastq.output.fastq
    output:
        gfa=f"results/02_assembly/{Read_id}.bp.p_ctg.gfa"
    threads: 15
    params:
        prefix=f"results/02_assembly/{Read_id}"
    wrapper:
        "0.85.0/bio/hifiasm"

# convert .gfa to .fa
rule convert_gfa:
    input:
        gfa=rules.de_novo.output.gfa
    output:
        fa=f"results/02_assembly/{Read_id}.bp.p_ctg.fa"
    shell:
        """
        awk '/^S/{print ">"$2"\n"$3}' {input.gfa} > {output.fa}
        """

# genome assembly quality check by quast
rule assembly_check1:
    input:
        assembly=rules.convert_gfa.output.fa
    output:
        report=f"results/03_quast/{Read_id}/report.html"
    threads: 15
    params:
        prefix=f"results/03_quast/{Read_id}"
    wrapper:
        "0.85.0/bio/quast"


        


